baseURL: http://pleonex.dev/

languageCode: en-us
title: "Pleotonic Engineering"
theme: "toha"

languages:
  en:
    languageName: "English"
    weight: 1

markup:
  tableOfContent:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
    - HTML
    - JSON
    - RSS

enableEmoji: true

params:
  background: "images/site/bg-moiry-river.webp"
  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/inverted-logo.png
    favicon: /images/site/favicon.png

  gitRepo: "https://github.com/pleonex/pleonex.github.io"
  gitBranch: "main"

  features:
    portfolio:
      enable: true
    blog:
      enable: false
      shareButtons:
        email: true
        mastodon: true
    notes:
      enable: false # GitBook
    comment:
      enable: false
    analytics:
      enable: false
    support:
      enable: false

  enableTOC: true
  enableTags: true

  footer:
    newsletter:
      enable: false

  darkMode:
    enable: true
    provider: darkreader
    default: system
